export const weatherStation = [
  {
    value: "WA",
    label: "Western Australia",
    children: [
      { value: 94210, label: "Adele Island" },
      { value: 94801, label: "Albany" },
      { value: 94802, label: "Albany Airport" },
      { value: 94217, label: "Argyle Aerodrome" },
      { value: 94603, label: "Badgingarra Research Stn" },
      { value: 94320, label: "Balgo Hills" },
      { value: 94642, label: "Balladonia" },
      { value: 95304, label: "Barrow Island Airport" },
      { value: 94310, label: "Bedout Island" },
      { value: 94632, label: "Bencubbin" },
      { value: 95615, label: "Beverley" },
      { value: 95610, label: "Bickley" },
      { value: 94202, label: "Bidyadanga" },
      { value: 95632, label: "Bridgetown" },
      { value: 94625, label: "Brookton" },
      { value: 94203, label: "Broome Airport" },
      { value: 95202, label: "Broome Ntc Aws" },
      { value: 94103, label: "Browse Island" },
      { value: 94444, label: "Bulga Downs" },
      { value: 94604, label: "Bunbury" },
      { value: 95630, label: "Busselton" },
      { value: 95611, label: "Busselton Aero" },
      { value: 95602, label: "Busselton Jetty" },
      { value: 94601, label: "Cape Leeuwin" },
      { value: 94600, label: "Cape Naturaliste" },
      { value: 94415, label: "Carnamah" },
      { value: 94300, label: "Carnarvon Airport" },
      { value: 94451, label: "Carnegie" },
      { value: 96995, label: "Christmas Island Aero" },
      { value: 96996, label: "Cocos Island Airport" },
      { value: 95621, label: "Collie East" },
      { value: 94633, label: "Corrigin" },
      { value: 95625, label: "Cunderdin Airfield" },
      { value: 94204, label: "Curtin Aero" },
      { value: 94201, label: "Cygnet Bay" },
      { value: 95629, label: "Dalwallinu" },
      { value: 94402, label: "Denham" },
      { value: 95205, label: "Derby Aero" },
      { value: 95622, label: "Donnybrook" },
      { value: 94215, label: "Doongan" },
      { value: 94620, label: "Dwellingup" },
      { value: 94318, label: "Emu Creek Station" },
      { value: 94414, label: "Eneabba" },
      { value: 94638, label: "Esperance" },
      { value: 95638, label: "Esperance Aero" },
      { value: 95648, label: "Esperance Ntc Aws" },
      { value: 94647, label: "Eucla" },
      { value: 94645, label: "Eyre" },
      { value: 94206, label: "Fitzroy Crossing Aero" },
      { value: 95646, label: "Forrest" },
      { value: 95607, label: "Garden Island Hsf" },
      { value: 94410, label: "Gascoyne Junction" },
      { value: 94403, label: "Geraldton Airport" },
      { value: 94461, label: "Giles Meteorological Office" },
      { value: 95612, label: "Gingin Aero" },
      { value: 95631, label: "Goomalling" },
      { value: 94615, label: "Gooseberry Hill" },
      { value: 95604, label: "Gosnells City" },
      { value: 94212, label: "Halls Creek Airport" },
      { value: 95605, label: "Hillarys Boat Harbour Ntc Aws" },
      { value: 95635, label: "Hopetoun North" },
      { value: 95627, label: "Hyden" },
      { value: 95620, label: "Inner Dolphin Pylon" },
      { value: 95636, label: "Jacup" },
      { value: 94609, label: "Jandakot Aero" },
      { value: 95623, label: "Jarrahwood" },
      { value: 95600, label: "Jurien Bay" },
      { value: 94401, label: "Kalbarri" },
      { value: 94637, label: "Kalgoorlie Boulder Airport" },
      { value: 94100, label: "Kalumburu" },
      { value: 95614, label: "Karnet" },
      { value: 95307, label: "Karratha Aero" },
      { value: 94641, label: "Katanning" },
      { value: 95603, label: "Kellerberrin" },
      { value: 94216, label: "Kununurra Aero" },
      { value: 95637, label: "Lake Grace" },
      { value: 95606, label: "Lancelin" },
      { value: 94449, label: "Laverton Aero" },
      { value: 94302, label: "Learmonth Airport" },
      { value: 94307, label: "Legendre Island" },
      { value: 95448, label: "Leinster Aero" },
      { value: 94448, label: "Leonora" },
      { value: 94450, label: "Leonora Aero" },
      { value: 94200, label: "Mandora" },
      { value: 94605, label: "Mandurah" },
      { value: 94617, label: "Manjimup" },
      { value: 95317, label: "Marble Bar" },
      { value: 94306, label: "Mardie" },
      { value: 95608, label: "Medina Research Centre" },
      { value: 94430, label: "Meekatharra Airport" },
      { value: 95624, label: "Merredin" },
      { value: 94417, label: "Morawa Airport" },
      { value: 94630, label: "Mount Barker" },
      { value: 94211, label: "Mount Elizabeth" },
      { value: 94429, label: "Mount Magnet Aero" },
      { value: 94411, label: "Mullewa" },
      { value: 95644, label: "Munglinup West" },
      { value: 94422, label: "Murchison" },
      { value: 95626, label: "Narembeen" },
      { value: 94627, label: "Narrogin" },
      { value: 94628, label: "Newdegate Research Station" },
      { value: 94317, label: "Newman Aero" },
      { value: 95642, label: "Norseman Aero" },
      { value: 94405, label: "North Island" },
      { value: 95647, label: "North Walpole" },
      { value: 94621, label: "Northam" },
      { value: 94607, label: "Ocean Reef" },
      { value: 95628, label: "Ongerup" },
      { value: 95305, label: "Onslow Airport" },
      { value: 94316, label: "Paraburdoo Aero" },
      { value: 94311, label: "Pardoo Station" },
      { value: 94404, label: "Paynes Find" },
      { value: 94612, label: "Pearce Raaf" },
      { value: 95613, label: "Pemberton" },
      { value: 94610, label: "Perth Airport" },
      { value: 94608, label: "Perth Metro" },
      { value: 95616, label: "Pingelly" },
      { value: 94312, label: "Port Hedland Airport" },
      { value: 94636, label: "Ravensthorpe" },
      { value: 94644, label: "Red Rocks Point" },
      { value: 94631, label: "Rocky Gully" },
      { value: 94308, label: "Roebourne Aero" },
      { value: 94602, label: "Rottnest Island" },
      { value: 94207, label: "Rowley Shoals" },
      { value: 95639, label: "Salmon Gums Res Stn" },
      { value: 95617, label: "Shannon" },
      { value: 95402, label: "Shark Bay Airport" },
      { value: 95634, label: "Southern Cross Airfield" },
      { value: 94614, label: "Swanbourne" },
      { value: 94319, label: "Telfer Aero" },
      { value: 94303, label: "Thevenard Island" },
      { value: 95316, label: "Tom Price" },
      { value: 94102, label: "Troughton Island" },
      { value: 95101, label: "Truscott" },
      { value: 95303, label: "Varanus Island" },
      { value: 95618, label: "Wagin" },
      { value: 95640, label: "Wandering" },
      { value: 94457, label: "Warburton Airfield" },
      { value: 94213, label: "Warmun" },
      { value: 95204, label: "West Roebuck" },
      { value: 94439, label: "Wiluna" },
      { value: 94640, label: "Windy Harbour" },
      { value: 95641, label: "Witchcliffe" },
      { value: 94622, label: "Wongan Hills" },
      { value: 95601, label: "Wongan Hills Res Station" },
      { value: 95214, label: "Wyndham Aero" },
      { value: 94440, label: "Yeelirrie" },
      { value: 94623, label: "York" },
    ],
  },
  {
    value: "NT",
    label: "Northern Territory",
    children: [
      { value: 94325, label: "Ali Curung" },
      { value: 94326, label: "Alice Springs Airport" },
      { value: 95323, label: "Arltunga" },
      { value: 94125, label: "Batchelor Airport" },
      { value: 94134, label: "Black Point" },
      { value: 94152, label: "Borroloola Airport" },
      { value: 94130, label: "Bradshaw" },
      { value: 94242, label: "Brunette Downs" },
      { value: 94143, label: "Bulman" },
      { value: 94147, label: "Cape Wessel" },
      { value: 94141, label: "Central Arnhem Plateau" },
      { value: 94248, label: "Centre Island" },
      { value: 94121, label: "Channel Point" },
      { value: 99510, label: "Charles Point" },
      { value: 94108, label: "Croker Island Airport" },
      { value: 94463, label: "Curtin Springs" },
      { value: 94234, label: "Daly Waters Airstrip" },
      { value: 94120, label: "Darwin Airport" },
      { value: 95122, label: "Darwin Ntc Aws" },
      { value: 94225, label: "Delamere Weapons Range" },
      { value: 94128, label: "Douglas River" },
      { value: 94116, label: "Dum In Mirrie Airstrip" },
      { value: 94236, label: "Elliott" },
      { value: 94114, label: "Fish Reef Marine" },
      { value: 94150, label: "Gove Airport" },
      { value: 94153, label: "Groote Eylandt Airport" },
      { value: 99501, label: "Gunn Point" },
      { value: 94137, label: "Jabiru Airport" },
      { value: 94327, label: "Jervois" },
      { value: 94132, label: "Katherine Country Club" },
      { value: 94466, label: "Kulgera" },
      { value: 94231, label: "Lajamanu Airport" },
      { value: 94237, label: "Larrimah" },
      { value: 94117, label: "Mango Farm" },
      { value: 95142, label: "Maningrida Airport" },
      { value: 94239, label: "Mcarthur River Mine Airport" },
      { value: 94135, label: "Mccluer Island" },
      { value: 95121, label: "Middle Point" },
      { value: 94140, label: "Milingimbi Airport" },
      { value: 94109, label: "Murganella Airstrip" },
      { value: 95146, label: "Ngayawili" },
      { value: 94106, label: "Ngukurr Airport" },
      { value: 94105, label: "Noonamah Airstrip" },
      { value: 94110, label: "Oenpelli Airport" },
      { value: 94322, label: "Papunya" },
      { value: 94119, label: "Pirlangimpi Airport" },
      { value: 94122, label: "Point Fawcett" },
      { value: 94127, label: "Point Stuart" },
      { value: 95111, label: "Port Keats Airport" },
      { value: 95322, label: "Rabbit Flat" },
      { value: 94238, label: "Tennant Creek Airport" },
      { value: 94328, label: "Territory Grape Farm" },
      { value: 94220, label: "Timber Creek" },
      { value: 94131, label: "Tindal Raaf" },
      { value: 94232, label: "Victoria River Downs" },
      { value: 94321, label: "Walungurru Airport" },
      { value: 94139, label: "Warruwi Airport" },
      { value: 94323, label: "Watarrka" },
      { value: 94229, label: "Wave Hill" },
      { value: 94258, label: "Wollogorang" },
      { value: 94324, label: "Yuendumu" },
      { value: 94462, label: "Yulara Airport" },
    ],
  },
  {
    value: "QLD",
    label: "Queensland",
    children: [
      { value: 95296, label: "Alva Beach" },
      { value: 94568, label: "Amberley Amo" },
      { value: 94553, label: "Applethorpe" },
      { value: 94575, label: "Archerfield Airport" },
      { value: 94284, label: "Arlington Reef" },
      { value: 95295, label: "Ayr Dpi Research Stn" },
      { value: 95487, label: "Ballera Gas Field" },
      { value: 94591, label: "Banana Bank North Beacon" },
      { value: 94350, label: "Barcaldine Post Office" },
      { value: 95575, label: "Beaudesert Drumley Street" },
      { value: 94334, label: "Bedourie Police Station" },
      { value: 95566, label: "Beerburrum Forest Station" },
      { value: 95482, label: "Birdsville Airport" },
      { value: 95351, label: "Blackall Airport" },
      { value: 94398, label: "Blackwater Airport" },
      { value: 94513, label: "Bollon Mary St" },
      { value: 95288, label: "Bougainville Reef" },
      { value: 94333, label: "Boulia Airport" },
      { value: 94576, label: "Brisbane" },
      { value: 94578, label: "Brisbane Aero" },
      { value: 94387, label: "Bundaberg Aero" },
      { value: 94260, label: "Burketown Airport" },
      { value: 94287, label: "Cairns Aero" },
      { value: 94288, label: "Cairns Racecourse" },
      { value: 94255, label: "Camooweal Township" },
      { value: 94297, label: "Cape Ferguson Ntc Aws" },
      { value: 94188, label: "Cape Flattery" },
      { value: 94594, label: "Cape Moreton Lighthouse" },
      { value: 94292, label: "Cardwell Marine Pde" },
      { value: 94394, label: "Cato Island" },
      { value: 94261, label: "Century Mine" },
      { value: 94510, label: "Charleville Aero" },
      { value: 94356, label: "Charters Towers Airport" },
      { value: 94395, label: "Clermont Airport" },
      { value: 94335, label: "Cloncurry Airport" },
      { value: 94182, label: "Coconut Island" },
      { value: 94183, label: "Coen Airport" },
      { value: 94360, label: "Collinsville Post Office" },
      { value: 95283, label: "Cooktown Airport" },
      { value: 94592, label: "Coolangatta" },
      { value: 94371, label: "Creal Reef" },
      { value: 94500, label: "Cunnamulla Post Office" },
      { value: 94542, label: "Dalby Airport" },
      { value: 94584, label: "Double Island Point Lighthouse" },
      { value: 94363, label: "Emerald Airport" },
      { value: 94290, label: "Flinders Reef" },
      { value: 94393, label: "Frederick Reef" },
      { value: 94379, label: "Gannet Cay" },
      { value: 95543, label: "Gayndah Airport" },
      { value: 94274, label: "Georgetown Airport" },
      { value: 94381, label: "Gladstone Airport" },
      { value: 94380, label: "Gladstone Radar" },
      { value: 94580, label: "Gold Coast Seaway" },
      { value: 94566, label: "Gympie" },
      { value: 94368, label: "Hamilton Island Airport" },
      { value: 99367, label: "Hay Point" },
      { value: 94386, label: "Heron Island Res Stn" },
      { value: 95565, label: "Hervey Bay Airport" },
      { value: 94289, label: "Holmes Reef" },
      { value: 94174, label: "Horn Island" },
      { value: 94343, label: "Hughenden Airport" },
      { value: 95291, label: "Ingham Composite" },
      { value: 94511, label: "Injune Post Office" },
      { value: 94590, label: "Inner Reciprocal Marker" },
      { value: 94291, label: "Innisfail" },
      { value: 94345, label: "Isisford Post Office" },
      { value: 94337, label: "Julia Creek Airport" },
      { value: 94549, label: "Kingaroy Airport" },
      { value: 94268, label: "Kowanyama Airport" },
      { value: 94388, label: "Lady Elliot Island" },
      { value: 94348, label: "Lake Julius Aws" },
      { value: 94293, label: "Lihou Reef Lighthouse" },
      { value: 94399, label: "Lochington" },
      { value: 94186, label: "Lockhart River Airport" },
      { value: 95581, label: "Logan City Water Treatment Plant" },
      { value: 94346, label: "Longreach Aero" },
      { value: 94285, label: "Low Isles Lighthouse" },
      { value: 94295, label: "Lucinda Point" },
      { value: 95367, label: "Mackay Aero" },
      { value: 94367, label: "Mackay M O" },
      { value: 94547, label: "Maleny Tamarind St" },
      { value: 95286, label: "Mareeba Airport" },
      { value: 94298, label: "Marion Reef" },
      { value: 94567, label: "Maryborough" },
      { value: 94372, label: "Middle Percy Island" },
      { value: 95529, label: "Miles Constance Street" },
      { value: 94514, label: "Mitchell Post Office" },
      { value: 94377, label: "Monto Township" },
      { value: 94397, label: "Moranbah Airport" },
      { value: 94254, label: "Mornington Island Airport" },
      { value: 94332, label: "Mount Isa Aero" },
      { value: 95572, label: "Nambour Daff Hillside" },
      { value: 94349, label: "New May Downs" },
      { value: 94266, label: "Normanton Airport" },
      { value: 94552, label: "Oakey Aero" },
      { value: 94276, label: "Palmerville" },
      { value: 94593, label: "Point Lookout" },
      { value: 94365, label: "Proserpine Airport" },
      { value: 94564, label: "Rainbow Beach" },
      { value: 95591, label: "Redcliffe" },
      { value: 94341, label: "Richmond Airport" },
      { value: 94374, label: "Rockhampton Aero" },
      { value: 94396, label: "Rolleston Airport" },
      { value: 94515, label: "Roma Airport" },
      { value: 95298, label: "Rosslyn Bay Ntc Aws" },
      { value: 94378, label: "Rundle Island" },
      { value: 94370, label: "Samuel Hill Aero" },
      { value: 94390, label: "Sandy Cape Lighthouse" },
      { value: 94171, label: "Scherger Raaf" },
      { value: 94384, label: "Seventeen Seventy" },
      { value: 95292, label: "South Johnstone Exp Stn" },
      { value: 94581, label: "Spitfire Channel Beacon" },
      { value: 95362, label: "Springsure Comet St" },
      { value: 94517, label: "St George Airport" },
      { value: 95369, label: "St Lawrence" },
      { value: 94550, label: "Stanthorpe Leslie Parade" },
      { value: 94569, label: "Sunshine Coast Airport" },
      { value: 94521, label: "Surat" },
      { value: 94257, label: "Sweers Island" },
      { value: 94355, label: "Tambo Post Office" },
      { value: 94525, label: "Taroom Post Office" },
      { value: 94570, label: "Tewantin Rsl Park" },
      { value: 95533, label: "Texas Post Office" },
      { value: 94376, label: "Thangool Airport" },
      { value: 95492, label: "Thargomindah Airport" },
      { value: 94336, label: "The Monument Airport" },
      { value: 95551, label: "Toowoomba Airport" },
      { value: 94294, label: "Townsville Aero" },
      { value: 94338, label: "Trepell Airport" },
      { value: 94562, label: "University Of Queensland Gatton" },
      { value: 94344, label: "Urandangi Aerodrome" },
      { value: 94555, label: "Warwick" },
      { value: 94170, label: "Weipa Aero" },
      { value: 95370, label: "Williamson" },
      { value: 94299, label: "Willis Island" },
      { value: 94342, label: "Winton Airport" },
      { value: 95293, label: "Woolshed" },
      { value: 94373, label: "Yeppoon The Esplanade" },
    ],
  },
  {
    value: "NSW",
    label: "New South Wales",
    children: [
      { value: 95748, label: "Albion Park Wollongong Airport" },
      { value: 95896, label: "Albury Airport Aws" },
      { value: 95773, label: "Armidale Airport Aws" },
      { value: 94773, label: "Armidale Tree Group Nursery" },
      { value: 94752, label: "Badgerys Creek Aws" },
      { value: 94596, label: "Ballina Airport Aws" },
      { value: 94696, label: "Balranald Rsl" },
      { value: 94765, label: "Bankstown Airport Aws" },
      { value: 94761, label: "Barraba Post Office" },
      { value: 94941, label: "Batemans Bay Catalina Country Club" },
      { value: 94730, label: "Bathurst Agricultural Station" },
      { value: 94729, label: "Bathurst Airport Aws" },
      { value: 95931, label: "Bega Aws" },
      { value: 94749, label: "Bellambi Aws" },
      { value: 94929, label: "Bombala Aws" },
      { value: 94928, label: "Bombala Therry Street" },
      { value: 94703, label: "Bourke Airport Aws" },
      { value: 94927, label: "Braidwood Racecourse Aws" },
      { value: 95512, label: "Brewarrina Hospital" },
      { value: 94691, label: "Broken Hill Airport Aws" },
      { value: 94689, label: "Broken Hill Patton Street" },
      { value: 94909, label: "Burrinjuck Dam" },
      { value: 94599, label: "Byron Bay Cape Byron Aws" },
      { value: 95916, label: "Cabramurra Smhea Aws" },
      { value: 94755, label: "Camden Airport Aws" },
      { value: 94757, label: "Campbelltown Mount Annan" },
      { value: 94926, label: "Canberra Airport" },
      { value: 94766, label: "Canterbury Racecourse Aws" },
      { value: 94573, label: "Casino Airport Aws" },
      { value: 95771, label: "Cessnock Airport Aws" },
      { value: 94710, label: "Cobar Airport Aws" },
      { value: 94711, label: "Cobar Mo" },
      { value: 95729, label: "Coffs Harbour Airport Comparison" },
      { value: 95520, label: "Collarenebri Albert St" },
      { value: 95708, label: "Condobolin Airport Aws" },
      { value: 94921, label: "Cooma Airport Aws" },
      { value: 94923, label: "Cooma Visitors Centre" },
      { value: 95728, label: "Coonabarabran Airport Aws" },
      { value: 94728, label: "Coonabarabran Namoi Street" },
      { value: 95718, label: "Coonamble Airport Aws" },
      { value: 95767, label: "Cooranbong Lake Macquarie Aws" },
      { value: 94714, label: "Cootamundra Airport" },
      { value: 95895, label: "Corowa Airport" },
      { value: 95721, label: "Cowra Airport Aws" },
      { value: 95869, label: "Deniliquin Airport Aws" },
      { value: 94789, label: "Dorrigo Old Coramba Rd" },
      { value: 95719, label: "Dubbo Airport Aws" },
      { value: 95727, label: "Dunedoo Post Office" },
      { value: 94598, label: "Evans Head Raaf Bombing Range Aws" },
      { value: 94715, label: "Forbes Airport Aws" },
      { value: 95778, label: "Forster Tuncurry Marine Rescue" },
      { value: 94769, label: "Fort Denison" },
      { value: 94686, label: "Fowlers Gap Aws" },
      { value: 94588, label: "Glen Innes Airport Aws" },
      { value: 94782, label: "Gosford Aws" },
      { value: 95716, label: "Goulburn Airport Aws" },
      { value: 94716, label: "Goulburn Tafe" },
      { value: 95570, label: "Grafton Airport Aws" },
      { value: 95571, label: "Grafton Research Stn" },
      { value: 94934, label: "Green Cape Aws" },
      { value: 94725, label: "Grenfell Manganese Rd" },
      { value: 95704, label: "Griffith Airport Aws" },
      { value: 94732, label: "Gulgong Post Office" },
      { value: 94890, label: "Gundagai William St" },
      { value: 95740, label: "Gunnedah Airport Aws" },
      { value: 94740, label: "Gunnedah Resource Centre" },
      { value: 94772, label: "Guyra Hospital" },
      { value: 94702, label: "Hay Airport Aws" },
      { value: 94700, label: "Hillston Airport" },
      { value: 95761, label: "Holsworthy Aerodrome Aws" },
      { value: 94760, label: "Horsley Park Equestrian Centre Aws" },
      { value: 94901, label: "Hume Reservoir" },
      { value: 95541, label: "Inverell Raglan St" },
      { value: 94541, label: "Inverell Research Centre" },
      { value: 95697, label: "Ivanhoe Aerodrome Aws" },
      { value: 95940, label: "Jervis Bay Point Perpendicular Aws" },
      { value: 94744, label: "Katoomba Murri St" },
      { value: 94785, label: "Kempsey Airport Aws" },
      { value: 94919, label: "Khancoban Aws" },
      { value: 95749, label: "Kiama Bombo Headland" },
      { value: 95756, label: "Kurnell Aws" },
      { value: 95707, label: "Lake Cargelligo Airport" },
      { value: 94692, label: "Lake Victoria Storage" },
      { value: 94498, label: "Lightning Ridge Visitors Information Cen" },
      { value: 94572, label: "Lismore Airport Aws" },
      { value: 94741, label: "Lithgow Cooerwull" },
      { value: 94780, label: "Little Bay The Coast Golf Club" },
      { value: 94995, label: "Lord Howe Island Aero" },
      { value: 95995, label: "Lord Howe Island Windy Point" },
      { value: 95772, label: "Lostock Dam" },
      { value: 95757, label: "Lucas Heights Aws" },
      { value: 95774, label: "Mangrove Mountain Aws" },
      { value: 95768, label: "Manly North Head" },
      { value: 94694, label: "Menindee Post Office" },
      { value: 95929, label: "Merimbula Airport Aws" },
      { value: 95754, label: "Merriwa Roscommon" },
      { value: 94939, label: "Montague Island Lighthouse" },
      { value: 95527, label: "Moree Aero" },
      { value: 95937, label: "Moruya Airport Aws" },
      { value: 94937, label: "Moruya Heads Pilot Station" },
      { value: 94746, label: "Moss Vale Aws" },
      { value: 94743, label: "Mount Boyce Aws" },
      { value: 95925, label: "Mount Ginini Aws" },
      { value: 94727, label: "Mudgee Airport Aws" },
      { value: 94520, label: "Mungindi Post Office" },
      { value: 95747, label: "Murrurundi Gap Aws" },
      { value: 94582, label: "Murwillumbah Bray Park" },
      { value: 95935, label: "Narooma Marine Rescue" },
      { value: 95734, label: "Narrabri Airport Aws" },
      { value: 95706, label: "Narrandera Airport" },
      { value: 95779, label: "Nelson Bay Nelson Head" },
      { value: 94943, label: "Nerriga Aws" },
      { value: 94774, label: "Newcastle Nobbys Signal Station Aws" },
      { value: 94781, label: "Newcastle University" },
      { value: 95770, label: "Norah Head Aws" },
      { value: 94996, label: "Norfolk Island Aero" },
      { value: 94750, label: "Nowra Ran Air Station Aws" },
      { value: 94754, label: "Nullo Mountain Aws" },
      { value: 94708, label: "Nyngan Airport" },
      { value: 95735, label: "Oberon Springbank" },
      { value: 95725, label: "Orange Agricultural Institute" },
      { value: 95726, label: "Orange Airport Aws" },
      { value: 95717, label: "Parkes Airport Aws" },
      { value: 94764, label: "Parramatta North Masons Drive" },
      { value: 94775, label: "Paterson Tocal Aws" },
      { value: 94721, label: "Peak Hill Post Office" },
      { value: 94763, label: "Penrith Lakes Aws" },
      { value: 94915, label: "Perisher Valley Aws" },
      { value: 94544, label: "Pindari Dam" },
      { value: 95692, label: "Pooncarie Mail Agency" },
      { value: 95745, label: "Port Kembla Ntc Aws" },
      { value: 94736, label: "Prospect Reservoir" },
      { value: 95746, label: "Quirindi Post Office" },
      { value: 95753, label: "Richmond Raaf" },
      { value: 95758, label: "Scone Airport Aws" },
      { value: 94738, label: "Scone Scs" },
      { value: 94733, label: "Singleton Stp" },
      { value: 94790, label: "South West Rocks Smoky Cape Lighthouse" },
      { value: 95744, label: "Springwood Valley Heights" },
      { value: 94767, label: "Sydney Airport Amo" },
      { value: 95766, label: "Sydney Harbour Wedding Cake West" },
      { value: 94768, label: "Sydney Observatory Hill" },
      { value: 95765, label: "Sydney Olympic Park Aws Archery Centre" },
      { value: 94587, label: "Tabulam Muirne" },
      { value: 95762, label: "Tamworth Airport Aws" },
      { value: 94735, label: "Taralga Post Office" },
      { value: 95784, label: "Taree Airport Aws" },
      { value: 95722, label: "Temora Airport" },
      { value: 94556, label: "Tenterfield Federation Park" },
      { value: 94759, label: "Terrey Hills Aws" },
      { value: 95909, label: "Thredbo Aws" },
      { value: 95908, label: "Thredbo Village" },
      { value: 95485, label: "Tibooburra Airport" },
      { value: 94877, label: "Tocumwal Airport" },
      { value: 95710, label: "Trangie Research Station Aws" },
      { value: 94925, label: "Tuggeranong Isabella Plains Aws" },
      { value: 94918, label: "Tumbarumba Post Office" },
      { value: 94938, label: "Ulladulla Aws" },
      { value: 94910, label: "Wagga Wagga Amo" },
      { value: 95715, label: "Walgett Airport Aws" },
      { value: 94497, label: "Wanaaring Post Office" },
      { value: 95752, label: "Wattamolla Aws" },
      { value: 94723, label: "Wellington Agrowplow" },
      { value: 95709, label: "West Wyalong Airport Aws" },
      { value: 95699, label: "White Cliffs Aws" },
      { value: 95695, label: "Wilcannia Aerodrome Aws" },
      { value: 94776, label: "Williamtown Raaf" },
      { value: 94792, label: "Woolbrook Danglemah Road" },
      { value: 94589, label: "Yamba Pilot Station" },
      { value: 95705, label: "Yanco Agricultural Institute" },
      { value: 94783, label: "Yarras Mount Seaview" },
      { value: 95723, label: "Yass Rural Fire Service" },
      { value: 94712, label: "Young Airport" },
    ],
  },
  {
    value: "TAS",
    label: "Tasmania",
    children: [
      { value: 95989, label: "Bicheno Council Depot" },
      { value: 95973, label: "Bridport Sea View Villas" },
      { value: 95975, label: "Bull Bay Lauriston" },
      { value: 95963, label: "Burnie Ntc Aws" },
      { value: 94958, label: "Burnie Round Hill" },
      { value: 94964, label: "Bushy Park Bushy Park Estates" },
      { value: 94959, label: "Butlers Gorge" },
      { value: 95972, label: "Campania Kincora" },
      { value: 95967, label: "Cape Bruny Cape Bruny" },
      { value: 94967, label: "Cape Bruny Lighthouse" },
      { value: 95954, label: "Cape Grim" },
      { value: 94974, label: "Cape Sorell" },
      { value: 94988, label: "Dennes Point" },
      { value: 95960, label: "Devonport Airport" },
      { value: 94961, label: "Dover" },
      { value: 94951, label: "Dunalley Stroud Point" },
      { value: 94980, label: "Flinders Island Airport" },
      { value: 94987, label: "Friendly Beaches" },
      { value: 94966, label: "Geeveston Cemetery Road" },
      { value: 95977, label: "Grove Research Station" },
      { value: 94977, label: "Hartz Mountain Keoghs Pimple" },
      { value: 94975, label: "Hobart Airport" },
      { value: 94970, label: "Hobart Ellerslie Road" },
      { value: 94949, label: "Hogan Island" },
      { value: 94850, label: "King Island Airport" },
      { value: 94979, label: "Lake Leake Elizabeth River" },
      { value: 94976, label: "Lake St Clair National Park" },
      { value: 94983, label: "Larapuna Eddystone Point" },
      { value: 95966, label: "Launceston Airport" },
      { value: 94969, label: "Launceston Ti Tree Bend" },
      { value: 95959, label: "Liawenee" },
      { value: 95964, label: "Low Head" },
      { value: 95961, label: "Low Rocky Point" },
      { value: 95956, label: "Luncheon Hill Forestry" },
      { value: 94962, label: "Maatsuyker Island Lighthouse" },
      { value: 95988, label: "Maria Island Point Lesueur" },
      { value: 94950, label: "Marrawah" },
      { value: 94963, label: "Maydena Post Office" },
      { value: 94971, label: "Melton Mowbray North Stockman" },
      { value: 95952, label: "Mount Read" },
      { value: 95979, label: "Mount Wellington" },
      { value: 95984, label: "Orford Aubin Court" },
      { value: 94957, label: "Ouse Fire Station" },
      { value: 94985, label: "Ross The Boulevards" },
      { value: 95958, label: "Scotts Peak Dam" },
      { value: 94972, label: "Scottsdale West Minstone Road" },
      { value: 94955, label: "Sheffield School Farm" },
      { value: 94953, label: "Smithton Aerodrome" },
      { value: 95987, label: "Spring Bay Ntc Aws" },
      { value: 95981, label: "St Helens Aerodrome" },
      { value: 94956, label: "Strahan Aerodrome" },
      { value: 95953, label: "Strathgordon Village" },
      { value: 95985, label: "Swan Island" },
      { value: 94981, label: "Swansea Francis Street" },
      { value: 95986, label: "Tasman Island" },
      { value: 94960, label: "Tunnack Fire Station" },
      { value: 95962, label: "Warra" },
      { value: 95957, label: "Wynyard Airport" },
    ],
  },
  {
    value: "VIC",
    label: "Victoria",
    children: [
      { value: 94846, label: "Aireys Inlet" },
      { value: 94834, label: "Ararat Prison" },
      { value: 94854, label: "Avalon Airport" },
      { value: 94912, label: "Bairnsdale Airport" },
      { value: 94852, label: "Ballarat Aerodrome" },
      { value: 94884, label: "Benalla Airport" },
      { value: 94855, label: "Bendigo Airport" },
      { value: 94857, label: "Breakwater Geelong Racecourse" },
      { value: 95873, label: "Bundoora Latrobe University" },
      { value: 94826, label: "Cape Nelson Lighthouse" },
      { value: 94842, label: "Cape Otway Lighthouse" },
      { value: 95825, label: "Casterton" },
      { value: 95853, label: "Castlemaine Prison" },
      { value: 94898, label: "Cerberus" },
      { value: 94839, label: "Charlton" },
      { value: 95845, label: "Colac Mount Gellibrand" },
      { value: 94864, label: "Coldstream" },
      { value: 94914, label: "Combienbar Aws" },
      { value: 94911, label: "Corner Inlet Yanakie" },
      { value: 94899, label: "Corryong Airport" },
      { value: 94879, label: "Cranbourne Botanic Gardens" },
      { value: 95822, label: "Dartmoor" },
      { value: 94888, label: "Dartmouth Reservoir" },
      { value: 94905, label: "Dinner Plain Mount Hotham Airport" },
      { value: 94861, label: "Echuca Aerodrome" },
      { value: 95832, label: "Edenhope Airport" },
      { value: 95838, label: "Edi Upper" },
      { value: 94881, label: "Eildon Fire Tower" },
      { value: 95866, label: "Essendon Airport" },
      { value: 94903, label: "Falls Creek" },
      { value: 95872, label: "Fawkner Beacon" },
      { value: 94872, label: "Ferny Creek" },
      { value: 94871, label: "Frankston Aws" },
      { value: 94933, label: "Gabo Island Lighthouse" },
      { value: 94913, label: "Gelantipy" },
      { value: 94833, label: "Grampians Mount William" },
      { value: 94829, label: "Hamilton Airport" },
      { value: 94838, label: "Hopetoun Airport" },
      { value: 95839, label: "Horsham Aerodrome" },
      { value: 94878, label: "Hunters Hill" },
      { value: 95827, label: "Kanagulk" },
      { value: 94844, label: "Kerang" },
      { value: 95833, label: "Kyabram" },
      { value: 94882, label: "Lake Eildon" },
      { value: 95904, label: "Lakes Entrance Eastern Beach Road" },
      { value: 94865, label: "Laverton Raaf" },
      { value: 95835, label: "Longerenong" },
      { value: 94935, label: "Mallacoota" },
      { value: 94874, label: "Mangalore Airport" },
      { value: 94849, label: "Maryborough" },
      { value: 94866, label: "Melbourne Airport" },
      { value: 95936, label: "Melbourne Olympic Park" },
      { value: 94693, label: "Mildura Airport" },
      { value: 94870, label: "Moorabbin Airport" },
      { value: 94840, label: "Mortlake Racecourse" },
      { value: 94891, label: "Morwell Latrobe Valley Airport" },
      { value: 95901, label: "Mount Baw Baw" },
      { value: 94894, label: "Mount Buller" },
      { value: 94906, label: "Mount Hotham" },
      { value: 95913, label: "Mount Moornapa" },
      { value: 94930, label: "Mount Nowa Nowa" },
      { value: 94827, label: "Nhill Aerodrome" },
      { value: 99806, label: "Nilma North Warragul" },
      { value: 94908, label: "Omeo" },
      { value: 95918, label: "Orbost" },
      { value: 94831, label: "Ouyen Post Office" },
      { value: 94883, label: "Phillip Island Penguin Reserve" },
      { value: 94932, label: "Point Hicks Lighthouse" },
      { value: 94847, label: "Point Wilson" },
      { value: 94830, label: "Port Fairy Aws" },
      { value: 94828, label: "Portland Cashmore Airport" },
      { value: 95826, label: "Portland Ntc Aws" },
      { value: 94886, label: "Pound Creek" },
      { value: 94835, label: "Pyrenees Ben Nevis" },
      { value: 94859, label: "Redesdale" },
      { value: 94892, label: "Rhyll" },
      { value: 95837, label: "Rutherglen Research" },
      { value: 95867, label: "Scoresby Research Institute" },
      { value: 94863, label: "Sheoaks" },
      { value: 94875, label: "Shepparton Airport" },
      { value: 94853, label: "South Channel Island" },
      { value: 95864, label: "St Kilda Harbour Rmys" },
      { value: 94836, label: "Stawell Aerodrome" },
      { value: 95843, label: "Strathbogie" },
      { value: 94843, label: "Swan Hill Aerodrome" },
      { value: 95836, label: "Tatura Inst Sustainable Ag" },
      { value: 95874, label: "Viewbank" },
      { value: 94860, label: "Wallan Kilmore Gap" },
      { value: 95831, label: "Walpeup Research" },
      { value: 94889, label: "Wangaratta Aero" },
      { value: 94837, label: "Warrnambool Airport Ndb" },
      { value: 95840, label: "Westmere" },
      { value: 94900, label: "Willow Grove Blue Rock Reservoir" },
      { value: 94893, label: "Wilsons Promontory Lighthouse" },
      { value: 95881, label: "Wonthaggi" },
      { value: 95890, label: "Yarram Airport" },
      { value: 94862, label: "Yarrawonga" },
    ],
  },
];
